[tool.poetry]
name = 'ascii_art'
version = '0.0.1'

[tool.poetry.dependencies]
python = '^3.6'
Pillows = '~8.4.0'

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"